name: Tutor_CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies(flake8 and pytest included)
      run: |
        ./bootstrap.sh
    - name: Lint with flake8
      run: |
        pipenv run flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=*venv* --extend-exclude=*migrations*
    - name: Test with pytest
      run: |
        pipenv run python3 -m pytest
